### PR TITLE
Compatibility with go1.11: Fix vendoring and function calls to dedis/kyber library

### PR DESCRIPTION
**Pull request by gabbifish**
Fixes https://github.com/dedis/drand/issues/70. Apologies for the large diff: this is due to my inclusion of the updated `vendor` directory, which includes the required version of `dedis/kyber` for go1.11 compatibility.

Some of the tests are failing because of timeouts that I can't pinpoint, and I'd love some help with this before thinking about a merge. The timeouts are also occurring in Travis, so you can check out the full stack trace there.
```
$ go test ./...
ok  	github.com/dedis/drand	1.387s
ok  	github.com/dedis/drand/beacon	(cached)
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/dedis/drand/core	600.043s
...
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/dedis/drand/dkg	600.037s
ok  	github.com/dedis/drand/ecies	(cached)
ok  	github.com/dedis/drand/fs	(cached)
ok  	github.com/dedis/drand/key	(cached)
ok  	github.com/dedis/drand/net	(cached)
?   	github.com/dedis/drand/protobuf/control	[no test files]
?   	github.com/dedis/drand/protobuf/crypto	[no test files]
?   	github.com/dedis/drand/protobuf/crypto/share	[no test files]
?   	github.com/dedis/drand/protobuf/crypto/share/vss	[no test files]
?   	github.com/dedis/drand/protobuf/dkg	[no test files]
?   	github.com/dedis/drand/protobuf/drand	[no test files]
?   	github.com/dedis/drand/test	[no test files]
```

### CODE REVIEW

**Comment by nikkolasg** [comment]
Thanks for your contributions ! It's surely my fault, I'm working on another branch of drand and have been updating the `group_info` branch on github as well, without thinking of compatbility with the drand's master branch. 
I'll try have a look later in the week to your branch. Timeouts should *not* occur locally though, but it happens that they occur in Travis, since they use a very power-limited VM and time plays a much higher factor in this context.

**Comment by gabbifish** [comment]
Hey @nikkolasg! The timeouts are happening locally, so it looks like there is an incompatibility between the latest commit on `dedis/kyber`'s `group_info` branch and the way drand calls/uses functions from this library. The `github.com/dedis/drand/core` test timeout seems linked to the following error, which precedes the timeouts:
```
dkg: 127.0.0.1:46229 sending deal to 127.0.0.1:45803
grpc-client: attempting connection to 127.0.0.1:45803 (TLS true)
dkg: 127.0.0.1:45803 processing deal from 127.0.0.1:46229 (1 processed)
dkg: error processing deal: schnorr: signature of invalid length 0 instead of 161
```
I'm still looking into what is potentially causing the `github.com/dedis/drand/dkg` timeout.

**Comment by nikkolasg** [comment]
Hey @gabbifish , sorry for the lack of active responses, I started a new job recently and it's hard to keep both activities going on in parallel.

I have changed the DKG code so it compiles at least on master, and I am looking at the DKG timeout this afternoon. Will let you know of any progress as soon as I have something :)

Thanks for looking into drand !

**Comment by nikkolasg** [comment]
Hey I've found the culprits, I'm doing a PR on master to at least get a stable master version.
https://github.com/dedis/drand/pull/72

**Comment by nikkolasg** [comment]
It's merged :) Let me know if you experience further issues with it ?

Just to let you know of the current context: There are two big features coming in the pipeline at the moment which are being **close** to completion (but ** not yet** !!):
+ Upgraded better CLI, something that will look like https://github.com/dedis/drand/issues/66 
+ Resharing protocol to be able to issue new shares to new group members very easily. The effect is that we'll be able afterwards to add new nodes to an already running drand group without changing the corresponding public key :)

**Comment by gabbifish** [comment]
These changes were rolled into #72, closing out issue #70

**Pull request closed without merging**
